### ISSUE TITLE
Ruby error

### ISSUE THREAD

**Issue by halian-vilela** [Yago/Cortana#12]
I'm getting this error when runnin hologram:

``` shell
$ hologram
Custom markdown renderer Cortanamarkdownrenderer loaded.
(erb):14:in `get_binding': undefined method `each' for nil:NilClass (NoMethodError)
    from /Users/aurus/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/erb.rb:850:in `eval'
    from /Users/aurus/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/erb.rb:850:in `result'
    from /Users/aurus/.rvm/gems/ruby-2.1.1@global/gems/hologram-1.2.0/lib/hologram/doc_builder.rb:187:in `write_page'
    from /Users/aurus/.rvm/gems/ruby-2.1.1@global/gems/hologram-1.2.0/lib/hologram/doc_builder.rb:171:in `block in write_docs'
    from /Users/aurus/.rvm/gems/ruby-2.1.1@global/gems/hologram-1.2.0/lib/hologram/doc_builder.rb:157:in `each'
    from /Users/aurus/.rvm/gems/ruby-2.1.1@global/gems/hologram-1.2.0/lib/hologram/doc_builder.rb:157:in `write_docs'
    from /Users/aurus/.rvm/gems/ruby-2.1.1@global/gems/hologram-1.2.0/lib/hologram/doc_builder.rb:123:in `build_docs'
    from /Users/aurus/.rvm/gems/ruby-2.1.1@global/gems/hologram-1.2.0/lib/hologram/doc_builder.rb:65:in `build'
    from /Users/aurus/.rvm/gems/ruby-2.1.1@global/gems/hologram-1.2.0/lib/hologram/cli.rb:38:in `build'
    from /Users/aurus/.rvm/gems/ruby-2.1.1@global/gems/hologram-1.2.0/lib/hologram/cli.rb:30:in `run'
    from /Users/aurus/.rvm/gems/ruby-2.1.1@global/gems/hologram-1.2.0/bin/hologram:6:in `<top (required)>'
    from /Users/aurus/.rvm/rubies/ruby-2.1.1/bin/hologram:23:in `load'
    from /Users/aurus/.rvm/rubies/ruby-2.1.1/bin/hologram:23:in `<main>'
    from /Users/aurus/.rvm/gems/ruby-2.1.1@global/bin/ruby_executable_hooks:15:in `eval'
    from /Users/aurus/.rvm/gems/ruby-2.1.1@global/bin/ruby_executable_hooks:15:in `<main>'
```

Don't know exactly what may be happening the YML is pretty identical to the example:

``` yml
# Hologram will run from same directory where this config file resides
# All paths should be relative to there

# The directory containing the source files to parse recursively
source: ./sass

# The directory that hologram will build to
destination: ./docs

# The assets needed to build the docs (includes header.html,
# footer.html, etc)
# You may put doc related assets here too: images, css, etc.
documentation_assets: ./bower_components/Cortana
custom_markdown: ./bower_components/Cortana/CortanaMarkdownRenderer.rb


# Any other asset folders that need to be copied to the destination
# folder. Typically this will include the css that you are trying to
# document. May also include additional folders as needed.
dependencies:
  - ./css

# Mark which category should be the index page
# Alternatively, you may have an index.md in the documentation assets
# folder instead of specifying this config.
index: basics

# String who is used to split the category name and create category wrapper
name_scope: ' - '

```

Any suggestion?

I'm using ruby 2.1.1 with rvm
